use [SKLAD30]
GO

GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON eqsUnit TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON eqsUnitFactor TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON eqsCategory TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON eqsSubCategory TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON eqsGroup TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE		  ON eqsItem TO [SKLAD30]
--revoke DELETE ON eqsItem TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON eqsGroup TO [SKLAD30]

GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON dbo.eqsArticle TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON dbo.eqsContractor TO [SKLAD30]
GRANT SELECT, REFERENCES					  ON dbo.eqsStorePointType TO [SKLAD30]
--revoke INSERT,UPDATE,DELETE ON eqsStorePointType TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON dbo.eqsStorePoint TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON dbo.eqsFinRespPerson TO [SKLAD30]

GRANT SELECT ON dbo.eqsStatus TO [SKLAD30]
GRANT SELECT ON dbo.eqsRegRemainsP TO [SKLAD30]
GRANT SELECT ON dbo.eqsRegRemainsR TO [SKLAD30]
GRANT SELECT ON dbo.eqsDocType TO [SKLAD30]

GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocument TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocArticleIn TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocIncoming TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocInitial TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocMove TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocOutgoing TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocRegrading TO [SKLAD30]
GRANT SELECT, REFERENCES,INSERT,UPDATE ON dbo.eqsDocWriteOff TO [SKLAD30]

GRANT SELECT, REFERENCES,INSERT,UPDATE,DELETE ON dbo.eqsDetail TO [SKLAD30]

GO
