USE [Chest35]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.tblScaffold(
	ID int IDENTITY(1,1) NOT NULL,
	Code varchar(10) NOT NULL,
	Decision nvarchar(255) NULL,
 CONSTRAINT [PK_tblScaffold] PRIMARY KEY CLUSTERED 
(
	ID ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [UIX_Scaffold_Code] ON [dbo].[tblScaffold] 
(
	[Code] ASC
)
INCLUDE ( [Decision]) WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
