

ALTER INDEX  ALL ON TableLogs REORGANIZE 
ALTER INDEX  TableLogs_idx7 ON TableLogs REORGANIZE 

USE [Chest35]
GO

/****** Object:  Index [TableLogs_idx7]    Script Date: 08/09/2019 09:06:47 ******/
CREATE NONCLUSTERED INDEX [TableLogs_idx7] ON [dbo].[TableLogs] 
(
	[SortID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
USE [Chest35]
GO

/****** Object:  Index [TableLogs_idx99]    Script Date: 08/09/2019 09:08:20 ******/
CREATE NONCLUSTERED INDEX [TableLogs_idx99] ON [dbo].[TableLogs] 
(
	[DateTime_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = OFF) ON [PRIMARY]
GO



ALTER INDEX  TableLogs_idx99 ON TableLogs set (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
ALTER INDEX  TableLogs_idx99 ON TableLogs REORGANIZE 
ALTER INDEX  ALL ON TableLogs REORGANIZE 

